//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NearHspt.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NearHspt.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just some Info.
        /// </summary>
        internal static string AlertFirstQuestionHd {
            get {
                return ResourceManager.GetString("AlertFirstQuestionHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why [Refresh] by me and not Auto?
        ///We are trying to save your Battery!
        ///
        ///Repeated auto calls to GPS can drain your battery rather fast.
        ///
        ///We want YOU in control of calls to GPS.
        ///   hurray   ---   BATTERY SAVED..
        /// </summary>
        internal static string AlertFisrtQuestion {
            get {
                return ResourceManager.GetString("AlertFisrtQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No GPS location data yet.
        ///
        ///Pressing [ Start / Refresh ], and you will have data within about 3 sexonds.
        ///.
        /// </summary>
        internal static string AlertNoHospitalYet {
            get {
                return ResourceManager.GetString("AlertNoHospitalYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Yet.
        /// </summary>
        internal static string AlertNoHospitalYetH {
            get {
                return ResourceManager.GetString("AlertNoHospitalYetH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not &apos;get&apos; GPS
        ///1) Current Internet acceess restricted (like &apos;free&apos; access)
        ///2) No Internet / Wi-Fi access
        ///
        ///A) Check &apos;Settings&apos;, &apos;Connections&apos;
        ///B)   Check Toolbar Menus (three-dots) for &apos;Tips&apos;, &apos;Troubleshooting&apos;.
        /// </summary>
        internal static string AlertNoInternet {
            get {
                return ResourceManager.GetString("AlertNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem getting GPS.
        /// </summary>
        internal static string AlertNoInternetHD {
            get {
                return ResourceManager.GetString("AlertNoInternetHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data, even after a minute?
        ///1) First, assure Internet Conectivity
        ///      Check out this app&apos;s Toolbar menus
        ///        (Upper right, three dots)
        ///2) Assure that &quot;Location&quot; is on:
        ///      * Tap on Phone [Settings],
        ///      *  next Tap on [Connections]
        ///      *  check \&quot;Locations\&quot; (must be ON).
        /// </summary>
        internal static string AlertNoLatLong {
            get {
                return ResourceManager.GetString("AlertNoLatLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting Location.
        /// </summary>
        internal static string AlertNoLatLonhd {
            get {
                return ResourceManager.GetString("AlertNoLatLonhd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device &apos;Location&apos; required, and Permission needed:
        ///
        ///the &apos;Location&apos; is used to get your position, and compare against a hospital position.
        ///
        ///See top Toolbar menu, &quot;Tips&quot; for more....
        /// </summary>
        internal static string AlertPermissionNeeded {
            get {
                return ResourceManager.GetString("AlertPermissionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Location&apos; Permission needed..
        /// </summary>
        internal static string AlertPermissionNeededHead1 {
            get {
                return ResourceManager.GetString("AlertPermissionNeededHead1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string Base_Private {
            get {
                return ResourceManager.GetString("Base Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string BaseAbout {
            get {
                return ResourceManager.GetString("BaseAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string BaseContact {
            get {
                return ResourceManager.GetString("BaseContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string BaseFeedback {
            get {
                return ResourceManager.GetString("BaseFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Does it Work?.
        /// </summary>
        internal static string BaseHowItWorks {
            get {
                return ResourceManager.GetString("BaseHowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (2)  How does it Work?.
        /// </summary>
        internal static string BaseHowItWorksHow {
            get {
                return ResourceManager.GetString("BaseHowItWorksHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (3)  Question about battery life..
        /// </summary>
        internal static string BaseHowItWorksSafe {
            get {
                return ResourceManager.GetString("BaseHowItWorksSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the application. 
        ///Tap [Start / Refresh ]
        ///
        ///(1) Your geolocation is generated.
        ///
        ///(2) Hospital database is prepared
        ///
        ///(3) Part of the database keyed to your location will now move into the app.
        ///
        ///(4) A particular Hospital selected.
        ///
        ///(5) A call goes out to Google to formulate, and show Hospital Details
        ///.
        /// </summary>
        internal static string BaseHowItWorksTxt2 {
            get {
                return ResourceManager.GetString("BaseHowItWorksTxt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Question?
        ///
        ///Our Promise:
        ///Our app will:
        ///
        ///** asked for permissions before we use certain functions
        ///
        ///** run geo scans in concise bursts, and save battery life
        ///
        ///** run a brief, targeted info-request blast to Google when a selected Hospital (name) needs updates, and save battery life.
        /// </summary>
        internal static string BaseHowItWorksTxt5Safe {
            get {
                return ResourceManager.GetString("BaseHowItWorksTxt5Safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1)  What is it?.
        /// </summary>
        internal static string BaseHowItWorksWhat {
            get {
                return ResourceManager.GetString("BaseHowItWorksWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application will:
        ///
        ///    * list the nearest Hospital(s), 
        ///       show distance, give many details
        ///
        ///
        ///  ** or gives you a list of all Hospital(s) in
        ///      100 miles surrounding (or 1st 100)
        ///*** lets you select a Hospital from the sorted list
        ///      and will show a Google-generated page with 
        ///      many hospital related details, including:
        ///
        ///
        ///(a) hospitals address, phone numbers
        ///
        ///(b) Driving Direction, web-site
        ///
        ///(c) medical and health capabilities
        ///
        ///(d) presence of an Emergency Department
        ///
        ///(e) R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseHowItWorksWhatisItText {
            get {
                return ResourceManager.GetString("BaseHowItWorksWhatisItText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application will:
        ///
        ///    * list the nearest Hospital(s), 
        ///       show distance, give many details
        ///
        ///
        ///  ** or gives you a list of all Hospital(s) in
        ///      100 miles surrounding (or 1st 100)
        ///*** lets you select a Hospital from the sorted list
        ///      and will show a Google-generated page with 
        ///      many hospital related details, including:
        ///
        ///
        ///(a) hospitals address, phone numbers
        ///
        ///(b) Driving Direction, web-site
        ///
        ///(c) medical and health capabilities
        ///
        ///(d) presence of an Emergency Department
        ///
        ///(e) R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseHowItWorksWhatText {
            get {
                return ResourceManager.GetString("BaseHowItWorksWhatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Disclaimer.
        /// </summary>
        internal static string BaseLegal {
            get {
                return ResourceManager.GetString("BaseLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can SORT the list on all columns
        ///
        ///-  Tap &apos;Miles&apos;, &apos;Beds&apos;, &apos;Name&apos;
        ///-  column will sort up/down
        ///-  an arrow to the right will tell direction
        ///.
        /// </summary>
        internal static string BaseListGuideSorting {
            get {
                return ResourceManager.GetString("BaseListGuideSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1)  How to Sort the List.
        /// </summary>
        internal static string BaseListGuideSortingHD {
            get {
                return ResourceManager.GetString("BaseListGuideSortingHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application will:
        ///
        ///  * list the nearest Hospital (name), 
        ///     show distance
        ///
        ///** or gives you a list of all Hospital (names) 
        ///     in 100 miles surrounding (or 1st 100)
        ///
        ///Select a Hospital (name) from a list, and a Google-generated page will show many details about the selected Hospital:
        ///
        ///(a) hospitals address, phone numbers
        ///
        ///(b) Driving Direction, web-site
        ///
        ///(c) medical and health capabilities
        ///
        ///(d) presence of an Emergency Department
        ///
        ///(e) RATING.
        /// </summary>
        internal static string BaseListGuideWhatDetails {
            get {
                return ResourceManager.GetString("BaseListGuideWhatDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (2)  What are the Details I see?.
        /// </summary>
        internal static string BaseListGuideWhatDetailsHD {
            get {
                return ResourceManager.GetString("BaseListGuideWhatDetailsHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share This App.
        /// </summary>
        internal static string BaseShare {
            get {
                return ResourceManager.GetString("BaseShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This seems to be a very useful app. 
        ///It gives you a list of hospitals centered around you current location. 
        ///The listed hospitals have a lot of details, and yes, they are RATED. 
        ///Take a look at 
        ///[https://www.cnginternetsoftware.com/smart_phone_software ].
        /// </summary>
        internal static string BaseShareText {
            get {
                return ResourceManager.GetString("BaseShareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        internal static string BaseTips {
            get {
                return ResourceManager.GetString("BaseTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Instant Silence&apos; is an option where you can NOW turn this buzzing off, even for a length of time
        ///
        ///(1) Bring up &apos;Starter - Phone Silence Page, i.e. 1st page
        ///(2) Select &apos;Silent on&apos;, select &apos;til when if needed
        ///  --  done; silent &apos;til:
        ///    -- press &apos;now Off&apos;, or
        ///    -- duration runs out.
        ///.
        /// </summary>
        internal static string BaseTipsInstantSilence {
            get {
                return ResourceManager.GetString("BaseTipsInstantSilence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY ADDRESS IS WRONG, WHY?
        ///GPS receivers use signals from satellites and sender on the ground to get a &apos;fix&apos; on your location. That information is merged (overlayed) on maps to get a &apos;named&apos; address. Two challenges:
        ///(1) sattelite and ground equipment signals can, and will, be interfered, and
        ///(2) maps go out of date.
        ///So, with these bottlenecks, an &apos;accurate&apos; address is at time off by as much as 60 feet.
        ///
        ///A Tip: Assure that the &quot;High accuracy&quot; setting is on. Go to &apos;Settings&apos;, &apos;Connections&apos;, &apos;Locations&apos;,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseTipsLocation {
            get {
                return ResourceManager.GetString("BaseTipsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1)  Google Geo Locations.
        /// </summary>
        internal static string BaseTipsLocationHD {
            get {
                return ResourceManager.GetString("BaseTipsLocationHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting User Access Permissions can be done in two ways:
        ///
        ///(1) via standard in-program message panels,
        ///
        ///(2) via &apos;outside&apos; general app Settings options.
        ///Start by finding and tapping the [ Settings ] icon
        ///Next:
        ///
        ///(a) tap &quot;Apps,&quot; tap &quot;All&quot; or &quot;Enabled&quot; option
        ///(b) scroll, find and tap on &quot;Phone Silence Area,&quot;
        ///(c) scroll, and find &quot;Permissions,&quot; set as required.
        /// </summary>
        internal static string BaseTipsPermissions {
            get {
                return ResourceManager.GetString("BaseTipsPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this app needs to &apos;work&apos; in areas suspected of transmission interferences, it can use some help.
        ///
        ///(1) Internet Connection ON, able to reach Googles Location Services
        ///(2) Turn &apos;high accuracy localization mode&apos; on (see next subject)
        ///(3) Turn Wi-Fi (Wi-Fi Scanning) on. Not having to relay just on cell info.
        ///(4) Turn GPS on (Warning, heavy battery use).
        ///.
        /// </summary>
        internal static string BaseTipsSmallArea {
            get {
                return ResourceManager.GetString("BaseTipsSmallArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting.
        /// </summary>
        internal static string BaseTrouble {
            get {
                return ResourceManager.GetString("BaseTrouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We collect NO personal information. 
        ///We collect NO payment information. 
        ///We collect NO Social Media Login Data. 
        ///We collect NO automatic data, such as IP addresses or device characteristics. 
        ///We collect NO private, personal information from other sources..
        /// </summary>
        internal static string BPrivacyBody1 {
            get {
                return ResourceManager.GetString("BPrivacyBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a resident of California, you are covered by California Civil Code Section 1798.83, known as the &quot;Shine The Light&quot; law. Your Rights include the request, free, once a year, of specific Information about personal Information if any collected. 
        ///Please contact us via email at service@CNGInternetSoftware.com regarding CA 1798.83.
        /// </summary>
        internal static string BPrivacyBody10 {
            get {
                return ResourceManager.GetString("BPrivacyBody10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, whenever it is necessary to stay legal. An updated &quot;Revised&quot; date will indicate the updated version..
        /// </summary>
        internal static string BPrivacyBody11 {
            get {
                return ResourceManager.GetString("BPrivacyBody11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any questions, any comments, please email us at Service@CNGInternetSoftware.com..
        /// </summary>
        internal static string BPrivacyBody12 {
            get {
                return ResourceManager.GetString("BPrivacyBody12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are not processing any personal, private information at all.
        /// </summary>
        internal static string BPrivacyBody2 {
            get {
                return ResourceManager.GetString("BPrivacyBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string BPrivacyBody3 {
            get {
                return ResourceManager.GetString("BPrivacyBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string BPrivacyBody4 {
            get {
                return ResourceManager.GetString("BPrivacyBody4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string BPrivacyBody5 {
            get {
                return ResourceManager.GetString("BPrivacyBody5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string BPrivacyBody6 {
            get {
                return ResourceManager.GetString("BPrivacyBody6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string BPrivacyBody7 {
            get {
                return ResourceManager.GetString("BPrivacyBody7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although we do not collect any information, you may contact us at service@CNGInternetSoftware.com regarding any discussion regarding privacy and personal data..
        /// </summary>
        internal static string BPrivacyBody8 {
            get {
                return ResourceManager.GetString("BPrivacyBody8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do-Not-Track (DNT) technology for mobile applications is not yet uniformly implemented. We currently do not recognize, collect, and process and respond to DNT..
        /// </summary>
        internal static string BPrivacyBody9 {
            get {
                return ResourceManager.GetString("BPrivacyBody9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. WHAT INFORMATION DO WE COLLECT?.
        /// </summary>
        internal static string BPrivacyHead1 {
            get {
                return ResourceManager.GetString("BPrivacyHead1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. CALIFORNIA RESIDENTS PRIVACY RIGHTS?.
        /// </summary>
        internal static string BPrivacyHead10 {
            get {
                return ResourceManager.GetString("BPrivacyHead10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. DO WE MAKE UPDATES TO THIS POLICY?.
        /// </summary>
        internal static string BPrivacyHead11 {
            get {
                return ResourceManager.GetString("BPrivacyHead11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12. HOW CAN YOU CONTACT US ABOUT THIS POLICY?.
        /// </summary>
        internal static string BPrivacyHead12 {
            get {
                return ResourceManager.GetString("BPrivacyHead12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. HOW DO WE USE YOUR INFORMATION?.
        /// </summary>
        internal static string BPrivacyHead2 {
            get {
                return ResourceManager.GetString("BPrivacyHead2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. WILL YOUR INFORMATION BE SHARED WITH ANYONE?.
        /// </summary>
        internal static string BPrivacyHead3 {
            get {
                return ResourceManager.GetString("BPrivacyHead3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. WHAT ABOUT COOKIES AND OTHER TRACKING TECHNOLOGIES?.
        /// </summary>
        internal static string BPrivacyHead4 {
            get {
                return ResourceManager.GetString("BPrivacyHead4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Does this software have/use logins from Social Media?.
        /// </summary>
        internal static string BPrivacyHead5 {
            get {
                return ResourceManager.GetString("BPrivacyHead5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. IS YOUR INFORMATION TRANSFERRED INTERNATIONALLY?.
        /// </summary>
        internal static string BPrivacyHead6 {
            get {
                return ResourceManager.GetString("BPrivacyHead6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. DO WE COLLECT INFORMATION FROM MINORS?.
        /// </summary>
        internal static string BPrivacyHead7 {
            get {
                return ResourceManager.GetString("BPrivacyHead7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. WHAT ARE YOUR PRIVACY RIGHTS?.
        /// </summary>
        internal static string BPrivacyHead8 {
            get {
                return ResourceManager.GetString("BPrivacyHead8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. DO WE RESPOND TO DO-NOT-TRACK SIGNALS?.
        /// </summary>
        internal static string BPrivacyHead9 {
            get {
                return ResourceManager.GetString("BPrivacyHead9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated [January 1st, 2020].
        /// </summary>
        internal static string BPrivacyLastUpdate {
            get {
                return ResourceManager.GetString("BPrivacyLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you downloading our mobile software. We will protect your Personal Information and your right to privacy. Any questions regarding your Personal Information, please contact us at service@CNGInternetSoftware.com
        ///This document will describe our privacy policy. We will explain to you what Information, if any, we collect, how it is (if received) used, and what your rights are. In case you do not agree with our Privacy Policy, please stop using this application.
        ///This privacy policy applies to all collecte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BPrivacyMainBody {
            get {
                return ResourceManager.GetString("BPrivacyMainBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Notice.
        /// </summary>
        internal static string BPrivacyTopHead {
            get {
                return ResourceManager.GetString("BPrivacyTopHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Location Access Denied.
        /// </summary>
        internal static string DisplayAlertPermissionDeniedHead2 {
            get {
                return ResourceManager.GetString("DisplayAlertPermissionDeniedHead2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate  -  Manage Profiles.
        /// </summary>
        internal static string EntryXamActivate {
            get {
                return ResourceManager.GetString("EntryXamActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Location.   Any Place, Any Room..
        /// </summary>
        internal static string EntryXamAllPlaces {
            get {
                return ResourceManager.GetString("EntryXamAllPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create A Profile.
        /// </summary>
        internal static string EntryXamCreate {
            get {
                return ResourceManager.GetString("EntryXamCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until:
        ///@ am/pm.
        /// </summary>
        internal static string EntryXamCutoff {
            get {
                return ResourceManager.GetString("EntryXamCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string EntryXamDuration {
            get {
                return ResourceManager.GetString("EntryXamDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Emergency&quot;
        ///Instant Silence.
        /// </summary>
        internal static string EntryXamInstantSilence {
            get {
                return ResourceManager.GetString("EntryXamInstantSilence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until:.
        /// </summary>
        internal static string EntryXamOnAgain {
            get {
                return ResourceManager.GetString("EntryXamOnAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional, max. 24hrs.
        /// </summary>
        internal static string EntryXamOptionalTime {
            get {
                return ResourceManager.GetString("EntryXamOptionalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  are used to define a Silent Area..
        /// </summary>
        internal static string EntryXamProfilesUsed {
            get {
                return ResourceManager.GetString("EntryXamProfilesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All other Hospitals / ER&apos;s, from your location, either:
        ///1 - First 100 count
        ///2 - or, First 100 miles.
        /// </summary>
        internal static string FindHLabelAllOther {
            get {
                return ResourceManager.GetString("FindHLabelAllOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing. To manage, TAP on a Profile..
        /// </summary>
        internal static string ListRuleHeader {
            get {
                return ResourceManager.GetString("ListRuleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    [Phone Silent Area] runs now normal,
        ///   i.e. with locations, Profiles
        ///
        ///.
        /// </summary>
        internal static string MainPageDeviceLocationGranted {
            get {
                return ResourceManager.GetString("MainPageDeviceLocationGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the distance, in miles, from your current location to the nearest Profile. 
        ///
        ///Why is that important?
        ///AI (Artificial Intelligence) at work. 
        ///If the phone is miles and miles from the most adjacent Profile, the App goes to sleep, waking up in a time when we are way closer. 
        ///
        ///So? 
        ///SAVING BATTERY POWER. 
        ///No draining of battery while &apos;looking&apos; for that Profile with a radius of 100ft, and we are 10 miles away. 
        ///
        ///Did I say AI at work?.
        /// </summary>
        internal static string MainPageFastExplanation {
            get {
                return ResourceManager.GetString("MainPageFastExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Silent.
        /// </summary>
        internal static string MainPageNotSilent {
            get {
                return ResourceManager.GetString("MainPageNotSilent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Silent.
        /// </summary>
        internal static string MainPageTurnSilent {
            get {
                return ResourceManager.GetString("MainPageTurnSilent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Profile(s) yet.
        /// </summary>
        internal static string MainPageXalmNoProfileYet {
            get {
                return ResourceManager.GetString("MainPageXalmNoProfileYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest Profile...:.
        /// </summary>
        internal static string MainPageXamlNearest {
            get {
                return ResourceManager.GetString("MainPageXamlNearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Profile(s) yet..
        /// </summary>
        internal static string NoProfileYet {
            get {
                return ResourceManager.GetString("NoProfileYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Get Milk.
        /// </summary>
        internal static string NotesPlaceholder {
            get {
                return ResourceManager.GetString("NotesPlaceholder", resourceCulture);
            }
        }
    }
}
